/*
* generated by Xtext
*/
package org.xtext.example.java.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.example.java.services.MyJava1GrammarAccess;

public class MyJava1Parser extends AbstractContentAssistParser {
	
	@Inject
	private MyJava1GrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.example.java.ui.contentassist.antlr.internal.InternalMyJava1Parser createParser() {
		org.xtext.example.java.ui.contentassist.antlr.internal.InternalMyJava1Parser result = new org.xtext.example.java.ui.contentassist.antlr.internal.InternalMyJava1Parser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getSmallClassAccess().getGroup(), "rule__SmallClass__Group__0");
					put(grammarAccess.getSmallClassAccess().getGroup_2(), "rule__SmallClass__Group_2__0");
					put(grammarAccess.getSmallClassAccess().getNameAssignment_1(), "rule__SmallClass__NameAssignment_1");
					put(grammarAccess.getSmallClassAccess().getSuperClassAssignment_2_1(), "rule__SmallClass__SuperClassAssignment_2_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.example.java.ui.contentassist.antlr.internal.InternalMyJava1Parser typedParser = (org.xtext.example.java.ui.contentassist.antlr.internal.InternalMyJava1Parser) parser;
			typedParser.entryRuleSmallClass();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public MyJava1GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MyJava1GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
