/*
* generated by Xtext
*/
package com.babu.xtext.cct.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.babu.xtext.cct.services.MyCCTGrammarAccess;

public class MyCCTParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MyCCTGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.babu.xtext.cct.parser.antlr.internal.InternalMyCCTParser createParser(XtextTokenStream stream) {
		return new com.babu.xtext.cct.parser.antlr.internal.InternalMyCCTParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "CCT";
	}
	
	public MyCCTGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MyCCTGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
