/*
 * generated by Xtext
 */
package org.xtext.example.java.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MyJava1UiModule extends org.xtext.example.java.ui.AbstractMyJava1UiModule {
	public MyJava1UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
