/*
 * generated by Xtext
 */
package com.babu.xtext.cct.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractMyCCTValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.babu.xtext.cct.myCCT.MyCCTPackage.eINSTANCE);
		return result;
	}
}
