/*
 * generated by Xtext
 */
package org.babu.xtext.training.smallfunc.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractSmallFuncDslValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.babu.xtext.training.smallfunc.smallFuncDsl.SmallFuncDslPackage.eINSTANCE);
		return result;
	}
}
