/*
 * generated by Xtext
 */
package org.babu.xtext.training.smalljava.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SmalljavaDslUiModule extends org.babu.xtext.training.smalljava.ui.AbstractSmalljavaDslUiModule {
	public SmalljavaDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
