/*
 * generated by Xtext
 */
package com.babu.xtext.cct.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MyCCTUiModule extends com.babu.xtext.cct.ui.AbstractMyCCTUiModule {
	public MyCCTUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
