/*
* generated by Xtext
*/
package org.xtext.example.java;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MyJava1StandaloneSetup extends MyJava1StandaloneSetupGenerated{

	public static void doSetup() {
		new MyJava1StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

