/*
 * generated by Xtext
 */
package org.xtext.example.java;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyJava1RuntimeModule extends org.xtext.example.java.AbstractMyJava1RuntimeModule {

}
