/*
 * generated by Xtext
 */
package org.xtext.example.java.ui.contentassist

import org.xtext.example.java.ui.contentassist.AbstractMyJava1ProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class MyJava1ProposalProvider extends AbstractMyJava1ProposalProvider {
}
