/*
* generated by Xtext
*/
package org.babu.xtext.training.smalljava.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.babu.xtext.training.smalljava.services.SmalljavaDslGrammarAccess;

public class SmalljavaDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SmalljavaDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.babu.xtext.training.smalljava.parser.antlr.internal.InternalSmalljavaDslParser createParser(XtextTokenStream stream) {
		return new org.babu.xtext.training.smalljava.parser.antlr.internal.InternalSmalljavaDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "NameSpace";
	}
	
	public SmalljavaDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SmalljavaDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
