/*
* generated by Xtext
*/
package org.babu.xtext.training.smalljava.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SmalljavaDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/babu/xtext/training/smalljava/parser/antlr/internal/InternalSmalljavaDsl.tokens");
	}
}
