/*
* generated by Xtext
*/
package com.babu.xtext.cct.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.babu.xtext.cct.services.MyCCTGrammarAccess;

public class MyCCTParser extends AbstractContentAssistParser {
	
	@Inject
	private MyCCTGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.babu.xtext.cct.ui.contentassist.antlr.internal.InternalMyCCTParser createParser() {
		com.babu.xtext.cct.ui.contentassist.antlr.internal.InternalMyCCTParser result = new com.babu.xtext.cct.ui.contentassist.antlr.internal.InternalMyCCTParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getCCTAccess().getGroup(), "rule__CCT__Group__0");
					put(grammarAccess.getFileAccess().getGroup(), "rule__File__Group__0");
					put(grammarAccess.getLoopAccess().getGroup(), "rule__Loop__Group__0");
					put(grammarAccess.getConditionAccess().getGroup(), "rule__Condition__Group__0");
					put(grammarAccess.getValueAccess().getGroup(), "rule__Value__Group__0");
					put(grammarAccess.getCCTAccess().getFileAssignment_0(), "rule__CCT__FileAssignment_0");
					put(grammarAccess.getCCTAccess().getLoopAssignment_1(), "rule__CCT__LoopAssignment_1");
					put(grammarAccess.getCCTAccess().getConditionAssignment_2(), "rule__CCT__ConditionAssignment_2");
					put(grammarAccess.getCCTAccess().getValueAssignment_3(), "rule__CCT__ValueAssignment_3");
					put(grammarAccess.getFileAccess().getNameAssignment_1(), "rule__File__NameAssignment_1");
					put(grammarAccess.getLoopAccess().getNameAssignment_1(), "rule__Loop__NameAssignment_1");
					put(grammarAccess.getConditionAccess().getNameAssignment_1(), "rule__Condition__NameAssignment_1");
					put(grammarAccess.getValueAccess().getNameAssignment_1(), "rule__Value__NameAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.babu.xtext.cct.ui.contentassist.antlr.internal.InternalMyCCTParser typedParser = (com.babu.xtext.cct.ui.contentassist.antlr.internal.InternalMyCCTParser) parser;
			typedParser.entryRuleCCT();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public MyCCTGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MyCCTGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
