/*
 * generated by Xtext
 */
package org.babu.xtext.training.smalljava.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.babu.xtext.training.smalljava.ui.internal.SmalljavaDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SmalljavaDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SmalljavaDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SmalljavaDslActivator.getInstance().getInjector(SmalljavaDslActivator.ORG_BABU_XTEXT_TRAINING_SMALLJAVA_SMALLJAVADSL);
	}
	
}
