/*
 * generated by Xtext
 */
package org.babu.xtext.training.smalljava;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SmalljavaDslRuntimeModule extends org.babu.xtext.training.smalljava.AbstractSmalljavaDslRuntimeModule {

}
