/*
* generated by Xtext
*/
package org.babu.xtext.training.smalljava;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SmalljavaDslStandaloneSetup extends SmalljavaDslStandaloneSetupGenerated{

	public static void doSetup() {
		new SmalljavaDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

