/*
* generated by Xtext
*/
package org.xtext.example.java;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MyJava1UiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.example.java.ui.internal.MyJava1Activator.getInstance().getInjector("org.xtext.example.java.MyJava1");
	}
	
}
