/*
 * generated by Xtext
 */
package org.xtext.example.java.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.example.java.ui.internal.MyJava1Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyJava1ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MyJava1Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MyJava1Activator.getInstance().getInjector(MyJava1Activator.ORG_XTEXT_EXAMPLE_JAVA_MYJAVA1);
	}
	
}
