/*
* generated by Xtext
*/
package org.xtext.example.java.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.java.services.MyJava1GrammarAccess;

public class MyJava1Parser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MyJava1GrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.example.java.parser.antlr.internal.InternalMyJava1Parser createParser(XtextTokenStream stream) {
		return new org.xtext.example.java.parser.antlr.internal.InternalMyJava1Parser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "SmallClass";
	}
	
	public MyJava1GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MyJava1GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
