/*
 * generated by Xtext
 */
package com.babu.xtext.cct.ui.contentassist

import com.babu.xtext.cct.ui.contentassist.AbstractMyCCTProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class MyCCTProposalProvider extends AbstractMyCCTProposalProvider {
}
