/*
* generated by Xtext
*/
package com.babu.xtext.cct;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MyCCTStandaloneSetup extends MyCCTStandaloneSetupGenerated{

	public static void doSetup() {
		new MyCCTStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

