/*
 * generated by Xtext
 */
package com.babu.xtext.cct;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyCCTRuntimeModule extends com.babu.xtext.cct.AbstractMyCCTRuntimeModule {

}
