/*
* generated by Xtext
*/
package com.babu.xtext.cct;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MyCCTUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.babu.xtext.cct.ui.internal.MyCCTActivator.getInstance().getInjector("com.babu.xtext.cct.MyCCT");
	}
	
}
